<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 */
?>
<?php if ($filter instanceof Magento\CatalogSearch\Model\Layer\Filter\Price || $filter instanceof Magento\Catalog\Model\Layer\Filter\Price): ?>
    <?php $range = $this->getPriceRange($filter); ?>
    <?php $url = $this->getFilterUrl($filter); ?>  
    <?php if (isset($range['min_standard'])) { ?>
        <div class="price-slider-wrap">
            <div id="price-slider" data-rate="<?php echo $range['rate']; ?>"
                 data-min-standard="<?php echo $range['min_standard'] ?>"
                 data-max-standard="<?php echo $range['max_standard'] ?>"></div>
            <div class="price-slider-values">
                <span class="filter-currency"><?php echo $range['currency_symbol']; ?></span>
                <input name="price_minimum" id="price_minimum" value="<?php echo $range['min_value'] ?>" type="text">
                <span class="price-filter-separator">&nbsp;-&nbsp;</span>
                <span class="filter-currency"><?php echo $range['currency_symbol']; ?></span>
                <input name="price_maximum" id="price_maximum" value="<?php echo $range['max_value'] ?>" type="text">
            </div>
        </div>
    <?php } ?>

    <!-- <script>
        var price_url = "<?php // echo $url; ?>";
        require([
            'jquery',
            "jquery/ui",
            'domReady!'
        ], function ($) {
    //     `use strict`;
            console.log("Price Slider..!");
            $("div#price-slider").slider({
                range: true,
                min: <?php // echo $range['min'] ?>,
                max: <?php // echo $range['max'] ?>,
                values: [<?php // echo $range['min'] ?>, <?php // echo $range['max'] ?>],
                slide: function (event, ui) {
                    $("#amount").val("$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ]);
                },
                change: function (event, ui) {
                    window.location.href = price_url + ui.values[0] + "-" + ui.values[1];
                }
            });
            $("#amount").val("$" + $("#price-slider").slider("values", 0) +
                    " - $" + $("#price-slider").slider("values", 1));
        });
    </script> -->
    <?php ?>    
    <!-- <p>
        <label for="amount">Price range:</label>
        <input type="text" id="amount" readonly style="border:0; color:#f6931f; font-weight:bold;">
    </p> -->
    <!-- <div id="price-slider"></div> -->
<?php else: ?>
<ol class="items">
    <?php foreach ($filterItems as $filterItem): ?>
        <li class="item">
            <?php if ($filterItem->getCount() > 0): ?>
                <a href="<?= $block->escapeUrl($filterItem->getUrl()) ?>">
                    <?= /* @escapeNotVerified */ $filterItem->getLabel() ?>
                    <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?= /* @escapeNotVerified */ $filterItem->getCount() ?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1):?> <?= /* @escapeNotVerified */ __('item') ?><?php else:?> <?= /* @escapeNotVerified */ __('items') ?><?php endif;?></span></span>
                    <?php endif; ?>
                </a>
            <?php else:?>
                <?= /* @escapeNotVerified */ $filterItem->getLabel() ?>
                <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                    <span class="count"><?= /* @escapeNotVerified */ $filterItem->getCount() ?><span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1):?><?= /* @escapeNotVerified */ __('item') ?><?php else:?><?= /* @escapeNotVerified */ __('items') ?><?php endif;?></span></span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>
<?php endif; ?>
