<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
   // print_r($objectManager->get('Magento\Framework\Registry')->registry('current_category'));//get current category);
    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
    // $category->addAttributeToSelect('*');
    // echo $category->getId();
    // echo $category->getName();

    // $categories = $objectManager->create('Magento\Catalog\Model\ResourceModel\Category\Collection');
    // $categories->addAttributeToSelect('*')
    // ->addAttributeToFilter('sm_show_in_cat_landing',['eq'=>1])
    // ->addAttributeToFilter('is_active',['eq'=>1])
    // ->setOrder('sm_show_in_cat_landing_order', 'ASC');
    $category_main = $objectManager->create('Magento\Catalog\Model\Category')->load($category->getId());
   // print_r($category_main->getAllChildren($category_main->getId()));
    $categories = $category_main->getChildrenCategories();
    // $categories->setOrder('sm_show_in_cat_landing_order', 'ASC');
    $tsk = 0;
    foreach($categories as $category):
    $_catId = $category->getEntityId();
    $catname = $category->getName();
    $caturl = $category->getUrl();
    $category = $objectManager->create('Magento\Catalog\Model\Category')
    ->load($_catId );

    if($category_main->getId() == 273 && ($tsk == 2 || $tsk == 3 || $tsk == 4 || $tsk == 5)) { 
      $subct = $category->getChildrenCategories(); 
      foreach ($subct as $one) {
         $catname = $one->getName();
         $caturl = $one->getUrl();
         $subcategories = $one->getChildrenCategories();
      }
    } 
    else { 
       $subcategories = $category->getChildrenCategories();
    }  
    $_outputhelper    = $this->helper('Magento\Catalog\Helper\Output');
    if(count($subcategories)):
    ?>
    <?php $media = str_replace("/index.php", "", $block->getBaseUrl()); ?>
    <div class="cat-pro-row">
            <div class="title-bar col-md-12"> <h2 class="main-title"> <?php echo $catname; ?> </h2>
            <a href="<?php echo $caturl; ?>">Shop All</a>
            <div class="brands-arrow pro-arrow">
			   <div class="owl-prev-h">&lt;</div>
			   <div class="owl-next-h">&gt;</div>
			</div>
        </div>
      	<div class="home-block slider-car pro-box-cat pro-p">
			      <div class="products-cat owl-carousel">
               <?php foreach ($subcategories as $subcategory) {
                    $subcategory = $objectManager->create('Magento\Catalog\Model\Category')->load($subcategory->getEntityId());
                    $_imgHtml   = '';
                    if ($_imgUrl = $subcategory->getImageUrl()) {
                        $_imgHtml = '<img src="' . $_imgUrl . '" alt="'.$subcategory->getName().'" title="'.$subcategory->getName().'" />';
                        $_imgHtml = $_outputhelper->categoryAttribute($subcategory, $_imgHtml, 'image');
                        
                    } else{$_imgHtml = '<img src="' .$media.'/pub/media/custom/default-img.jpg"/>'; } ?>
                    <div class="item">
					          <div class="pro-main-box">
                        <a href="<?php echo $subcategory->getUrl(); ?>">
                            <?php echo $_imgHtml; ?>
                            <h5><?php echo $subcategory->getName(); ?></h5>
                        </a>
                    </div>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
   <?php
   else:
     $media = str_replace("/index.php", "", $block->getBaseUrl());
    ?> 
      <div class="cat-pro-row">
            <div class="title-bar col-md-12"> <h2 class="main-title"> <?php echo $catname; ?> </h2>
            <a href="<?php echo $caturl; ?>">Shop All</a>
            <div class="brands-arrow pro-arrow">
               <div class="owl-prev-h">&lt;</div>
               <div class="owl-next-h">&gt;</div>
            </div>
        </div>
        <div class="home-block slider-car pro-box-cat pro-p">
            <div class="products-cat owl-carousel">
                  <?php  
                  $category = $objectManager->create('Magento\Catalog\Model\Category')->load($category->getEntityId());
                    $_imgHtml   = '';
                    if ($_imgUrl = $category->getImageUrl()) {
                        $_imgHtml = '<img src="' . $_imgUrl . '" alt="'.$catname.'" title="'.$catname.'" />';
                        $_imgHtml = $_outputhelper->categoryAttribute($category, $_imgHtml, 'image');
                        
                    } else{$_imgHtml = '<img src="' .$media.'/pub/media/custom/default-img.jpg"/>'; } 
                    ?>
                    <div class="item">
                       <div class="pro-main-box">
                        <a href="<?php echo $caturl ?>">
                            <?php echo $_imgHtml; ?>
                            <h5><?php echo $catname; ?></h5>
                        </a>
                    </div>
                 </div>
            </div>
       </div>
    </div> 

  <?php 
    endif;
    $tsk++;
     endforeach; ?>
