  <div class="header-bottom-mob">
          <div class="container">
            <div class="col-md-12 col-sm-12 col-xs-12">
            <label> Select Category </label>
            <select class="sel-cat">
                <option> All Categories </option>
                <option> Dog </option>
                <option> Cat </option>
                <option> Small Pet </option>
                <option> Reptiles </option>
            </select>
            </div>
          </div>
  </div> 