<?php
/*------------------------------------------------------------------------
# SM Categories - Version 3.2.0
# Copyright (c) 2016 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

$list = $this->_getList();

$categoriesIds = $this->getSelectCategory();
$categoriesIds = explode(',', $categoriesIds);

if (!empty($list)) {
    $_config           = $this->helper('Sm\Market\Helper\Data');
    $enableLadyLoading = $_config->getAdvanced('enable_ladyloading');
    $mediaSrc          = $_config->getMediaUrl();

    if ($enableLadyLoading) {
        $imgClass = 'lazyload';
    } else {
        $imgClass = '';
    }
    ?>
    <?php if (!empty($this->_getConfig('title_module'))) { ?>
        <!-- <div class="title-home-page">
            <span><?php // echo $this->_getConfig('title_module'); ?></span>
        </div> -->
    <?php } ?>
         <?php /*foreach ($list as $item) { ?>
                 <div class="col-md-2 col-sm-2 col-xs-6 cat-main-name">
                            <?php if ($item['cat_image']) { ?>
                                <div class="image-cat static-image 11">
                                    <a href="<?php echo $item['url'] ?>" title="<?php echo $item['name'] ?>">
                                        <img class="<?php echo $imgClass; ?>"
                                            <?php if ($enableLadyLoading) { ?>
                                                src="<?php echo $mediaSrc . 'lazyloading/blank.png'; ?>"
                                                data-src="<?php echo $item['cat_image']; ?>"
                                            <?php } else { ?>
                                                src="<?php echo $testImage; ?>"
                                            <?php } ?>
                                           alt="<?php echo $item['name'] ?>"
                                        />
                                    <h3> <?php echo $item['name']; ?></h3>
                                    </a>
                                </div>
                            <?php  } else { ?>
                                 <div class="image-cat static-image 222">
                                    <a href="<?php echo $item['url'] ?>" title="<?php echo $item['name'] ?>">
                                        <img class="<?php echo $imgClass; ?>"
                                            <?php if ($enableLadyLoading) { ?>
                                                src="<?php echo $mediaSrc . 'lazyloading/blank.png'; ?>"
                                                data-src="<?php echo $mediaSrc . 'custom/default-img.jpg'; ?>"
                                            <?php } else { ?>
                                                src="<?php echo $mediaSrc . 'custom/default-img.jpg'; ?>"
                                            <?php } ?>
                                           alt="<?php echo $item['name'] ?>"
                                        />
                                    <h3> <?php echo $item['name']; ?></h3>
                                    </a>
                                </div>
                            <?php } ?>
                    </div>
            <?php } */ ?>



            <?php foreach ($categoriesIds as $categoryId) { 

                $_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $category = $_objectManager->create('Magento\Catalog\Model\Category')->load($categoryId);

                ?>
                 <div class="col-md-2 col-sm-2 col-xs-6 cat-main-name">
                            <?php if ($category->getImage()) { ?>
                                <div class="image-cat static-image 11">
                                    <a href="<?php echo $category->getUrl(); ?>" title="<?php echo $category->getName(); ?>">
                                        <img class="image"
                                                src="<?php echo '/pub/media/catalog/category/' . $category->getImage(); ?>"
                                           alt="<?php echo $category->getName() ?>"
                                        />
                                    <h3> <?php echo $category->getName(); ?></h3>
                                    </a>
                                </div>
                            <?php  } else { ?>
                                 <div class="image-cat static-image 222">
                                    <a href="<?php echo $category->getUrl(); ?>" title="<?php echo $category->getName(); ?>">
                                        <img class="<?php echo $imgClass; ?>"
                                            <?php if ($enableLadyLoading) { ?>
                                                src="<?php echo $mediaSrc . 'lazyloading/blank.png'; ?>"
                                                data-src="<?php echo $mediaSrc . 'custom/default-img.jpg'; ?>"
                                            <?php } else { ?>
                                                src="<?php echo $mediaSrc . 'custom/default-img.jpg'; ?>"
                                            <?php } ?>
                                           alt="<?php echo $category->getName(); ?>"
                                        />
                                    <h3> <?php echo $category->getName(); ?></h3>
                                    </a>
                                </div>
                            <?php } ?>
                    </div>
            <?php } ?>


    <?php
} else { ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
            echo __('We can\'t find categories matching the selection.') ?></div>
    </div>
    <?php
} ?>
