<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>
<div data-block="minicart" class="minicart-wrapper cartwarpmob">
    <a class="action showcart_mobile" href="<?php /* @escapeNotVerified */
    echo $block->getShoppingCartUrl(); ?>"
       data-bind="scope: 'minicart_content'">
            <!-- ko if: getCartParam('summary_count') == 0 -->
            <!-- /ko -->
        <span class="counter qty empty"
              data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
            <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
            <span class="counter-label">
			<!-- ko if: getCartParam('summary_count') -->
                <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                <!-- ko i18n: 'items' --><!-- /ko -->
                <!-- /ko -->

                <!-- ko if: getCartParam('summary_count') == 0 -->
                <!-- ko i18n: '0 item' --><!-- /ko -->
                <!-- /ko -->
            </span>
        </span>
    </a>
    <script>
        window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */
        echo $block->getJsLayout(); ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */
        echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
    <script type="text/javascript">
      require(["jquery"],function($){
      });
    </script>
</div>