<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Address\Edit $block */
?>
<!--------------- For OTP ----------------->
<div id="editaddress_modal" style="display: none;">
    <h1 class="modal-title">Mobile Number Verification</h1>
    <p class="note-cod required">
        <span id="otp_send_confirm"></span>
        <span id="mobileNumber_otp"></span>
    </p>
    <p><b id="timer_run"></b></p>
    <div role="alert" class="messages otp-success" style="display: none">
      <div class="message-success success message" data-ui-id="message-success">
        <div>
         <span id="success-valid-code"></span>
        </div>
      </div>
    </div>
    <div role="alert" class="messages otp-error" style="display:none;">
        <div class="message-error error message" data-ui-id="message-error">
            <div>
            <span id="empty-invalid-otp"></span>
            </div>
        </div>
    </div>
    <input class="input-text" type="number" name="verify_number" aria-required="true"  id="opt-number" placeholder="Enter OTP">
    <input type="hidden" id="checkout_flag" value="0" class=""/>
    <input type="hidden" id="counter_timer" value="120" class=""/>
    <div class="opt-error-msg"></div>
</div>
<!--------------- For OTP ----------------->
<?php $_company = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Company') ?>
<?php $_telephone = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Telephone') ?>
<?php $_fax = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Fax') ?>
<?php // echo $block->getAddress()->getId(); ?>
<form class="form-address-edit"
      action="<?= $block->escapeUrl($block->getSaveUrl()) ?>"
      method="post"
      id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Contact Information')) ?></span></legend><br>
        <?= $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">
        <?= $block->getNameBlockHtml() ?>

        <?php if ($_company->isEnabled()): ?>
            <?= $_company->setCompany($block->getAddress()->getCompany())->toHtml() ?>
        <?php endif ?>

        <?php if ($_telephone->isEnabled()): ?>
            <?php // if($block->getAddress()->getTelephone()): ?>
            <?php /* echo $_telephone->setTelephone($block->getAddres()->getTelephone())->toHtml() */ ?>
            <?php // else: ?>
            <?php // echo donothing ?>
            <?php // endif ?>
        <?php endif ?>

        <?php if ($_fax->isEnabled()): ?>
            <?= $_fax->setFax($block->getAddress()->getFax())->toHtml() ?>
        <?php endif ?>

    </fieldset>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Address')) ?></span></legend><br>
        <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>
        <div class="field street required">
            <label for="street_1" class="label">
                <!-- <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?></span> -->
                <span>Street/Villa - Tower/Flat</span>
            </label>
            <div class="control">
                <input type="text"
                       name="street[]"
                       value="<?= $block->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                       title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?>"
                       id="street_1"
                       class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>"/>
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 1, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i < $_n; $_i++): ?>
                        <div class="field additional">
                            <?php if($_i == 1) { ?>
                            <label class="extra-label" for="street_<?= /* @noEscape */ $_i + 1 ?>">
                                <span><?= $block->escapeHtml(__('Street/Villa Line 2')) ?></span>
                            </label>
                            <?php } else { ?>
                            <label class="label" for="street_<?= /* @noEscape */ $_i + 1 ?>">
                                <span><?= $block->escapeHtml(__('Street Address %1', $_i + 1)) ?></span>
                            </label>                             
                           <?php } ?>
                            <div class="control">
                                <input type="text" name="street[]"
                                       value="<?= $block->escapeHtmlAttr($block->getStreetLine($_i + 1)) ?>"
                                       title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i + 1)) ?>"
                                       id="street_<?= /* @noEscape */ $_i + 1 ?>"
                                       class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>

        <?php if ($this->helper('Magento\Customer\Helper\Address')->isVatAttributeVisible()) : ?>
            <div class="field taxvat">
                <label class="label" for="vat_id">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="vat_id"
                           value="<?= $block->escapeHtmlAttr($block->getAddress()->getVatId()) ?>"
                           title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?>"
                           class="input-text <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('vat_id')) ?>"
                           id="vat_id">
                </div>
            </div>
        <?php endif; ?>

        <div class="field area">
            <label class="label" for="area"><span><?php echo $block->escapeHtml(__('Area')) ?></span></label>
            <div class="control">
               <?php $area = $block->getAddress()->getCustomAttribute('area'); if($area = $block->getAddress()->getCustomAttribute('area')) {
                        $areaval = $area->getValue();
                    }  else { $areaval = ''; }?>
                <input type="text" name="area" value="<?php echo $block->escapeHtmlAttr($areaval); ?>" title="<?php echo $block->escapeHtmlAttr(__('Area')) ?>" class="input-text <?php echo $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('area')) ?>" id="area">
            </div>
        </div>

        <div class="field city required">
            <label class="label" for="city"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span></label>
            <div class="control">
                <input type="text"
                       name="city"
                       value="<?= $block->escapeHtmlAttr($block->getAddress()->getCity()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('City')) ?>"
                       class="input-text <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city')) ?>"
                       id="city">
            </div>
        </div>
        <?php if(!$block->getConfig('general/region/display_all')) { } else { ?>
        <div class="field region required">
            <label class="label" for="region_id">
                <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?></span>
            </label>
            <div class="control">
                <select id="region_id" name="region_id"
                        title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>"
                        class="validate-select region_id" <?= /* @noEscape */ !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>>
                    <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                </select>
                <input type="text"
                       id="region"
                       name="region"
                       value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>"
                       title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>"
                       class="input-text validate-not-number-first <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region')) ?>"<?= !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>/>
            </div>
        </div>
        <?php } ?>
        <!-- <div class="field zip required">
            <label class="label" for="zip">
                <span><?php /* @noEscape */ /* $block->getAttributeData()->getFrontendLabel('postcode') */ ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="postcode"
                       value="<php /* $block->escapeHtmlAttr($block->getAddress()->getPostcode()) */ ?>"
                       title="<php /* @noEscape */ /* $block->getAttributeData()->getFrontendLabel('postcode') */ ?>"
                       id="zip"
                       class="input-text validate-zip-international <php /* $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode')) */ ?>">
                <div role="alert" class="message warning" style="display:none">
                    <span></span>
                </div>
            </div>
        </div> -->
        <div class="field country required">
            <label class="label" for="country"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span></label>
            <div class="control">
                <?= $block->getCountryHtmlSelect() ?>
            </div>
        </div>

        <?php if ($block->isDefaultBilling()): ?>
            <!-- <div class="message info">
                <span><?php /* $block->escapeHtml(__("It's a default billing address.")) */ ?></span>
            </div> -->
        <?php elseif ($block->canSetAsDefaultBilling()): ?>
                <input type="checkbox" style="visibility: hidden;" id="primary_billing" name="default_billing" value="1" class="checkbox">
        <?php else: ?>
            <input type="hidden" name="default_billing" value="1" />
        <?php endif; ?>

        <?php if ($block->isDefaultShipping()): ?>
            <div class="message info">
                <span><?= $block->escapeHtml(__("It's a default shipping address.")) ?></span>
            </div>
        <?php elseif ($block->canSetAsDefaultShipping()): ?>
            <div class="field choice set shipping">
                <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox">
                <label class="label" for="primary_shipping">
                    <span><?= $block->escapeHtml(__('Use as my default shipping address')) ?></span>
                </label>
            </div>
        <?php else: ?>
            <input type="hidden" name="default_shipping" value="1">
        <?php endif; ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    class="action save primary"
                    data-action="save-address"
                    id="save-edit-address"
                    title="<?= $block->escapeHtmlAttr(__('Save Address')) ?>">
                <span><?= $block->escapeHtml(__('Save Address')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $block->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {
                "postCodes": <?= /* @noEscape */ $block->getPostCodeConfig()->getSerializedPostCodes(); ?>
            }
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= (int) $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<script>
      require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal',
            'js/sms-otp'
        ],
        function($,modal) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                modalClass: 'otp-modal',
                buttons: [{
                    text: $.mage.__('Verify OTP'),
                    attr: { 
                          id: 'opt_checkout'
                    },
                    class: 'action primary',
                    click: function (event) {
                        haveverify(event);
                    }
                }, {
                    text: $.mage.__('Resend SMS'),
                    attr: {
                           id: 'opt_SMS' 
                    },
                    class: 'action primary',
                    click: function (event) {
                        haveresend(event);
                    }
                }]
            };

            // openeing modal
            var dataForm = $('#form-validate');
            var popup = modal(options, $('#editaddress_modal'));
            $("#save-edit-address").on("click",function(e){
               var numbr_current_value = $("input[name=telephone]").val();
               var customer_value = <?php if($_telephone->escapeHtmlAttr($_telephone->getTelephone()) != '') { echo $_telephone->escapeHtmlAttr($_telephone->getTelephone()); } else { echo '""'; } ?>;
               // If phone number id same
               if(numbr_current_value == customer_value) {
                   // trigger and go ahead for submitting data
                   $( "#form-validate" ).submit();
               }
               // If phone number is not same
               else {
                   // open modal to confirm the number
                   if(dataForm.validation('isValid')) {
                    e.preventDefault();
                    if($(".customer_ph_number").val().substr(0, 2) != 05) {
                    $(".customer_ph_number").after('<span style="color:red" class="error">Phone Number is invalid must starts with 05.</span>');
                    $(".customer_ph_number").focus();
                    }
                    else {
                        if($('#checkout_flag').val() == 1) { 
                        // submit the edit address
                        $( "#form-validate" ).submit();
                        }
                        else {
                            e.preventDefault();
                            $('#editaddress_modal').modal('openModal');
                            <?php if($block->getAddress()->getId()) { $event = 'EditAdrress'; } else { $event = 'NewAdrress'; } ?>
                            smsmodal('<?php echo $event; ?>');
                        }
                    }
                   }
               }
            });

             // function for sending SMS
            function smsmodal(event) {
                $num = $("input[name=telephone]").val();
                $.ajax({
                    headers: { "Accept": "application/json"},
                    type: 'POST',
                    url: 'https://www.thepetstore.ae/sms.php?method=1&phone='+$num+'&event='+event,
                    crossDomain: true,
                    beforeSend: function(xhr){
                        xhr.withCredentials = true;
                    },
                    success: function(data, textStatus, request){
                        // $(".modal-title").text("OPT have sent to You");
                        $("#otp_send_confirm").text("An OTP (One Time Passcode) has been sent to");
                        $("#mobileNumber_otp").text($num + '. ' + 'Please enter the OTP in the field below to verify.');
                        refrence_number = data;
                        var timeLeft = 120;
                        var elem = document.getElementById('modal-title-0');
                        var timer_elem = document.getElementById('timer_run');
                        $("#opt_SMS").attr("disabled", true);
                        // var timerId = setInterval(countdown, 1000);
                        var timerId;
                        timerId = setInterval(countdown, 1000);
                        var timeLeft = document.getElementById('counter_timer').value;
                        
                        function countdown() {
                            if (timeLeft == 0) {
                                clearTimeout(timerId);
                                timer_elem.innerHTML = 'Token Expire';
                                document.getElementById('counter_timer').value = timeLeft;
                            $("#opt_SMS").removeAttr("disabled");
                            } else {
                                timer_elem.innerHTML = timeLeft + ' seconds remaining';
                                timeLeft--;
                                document.getElementById('counter_timer').value = timeLeft;
                            }
                        }

                    },error: function (jqXHR, exception) {
                        var msg = '';
                        if (jqXHR.status === 0) {
                            msg = 'Not connect.\n Verify Network.';
                        } else if (jqXHR.status == 404) {
                            msg = 'Requested page not found. [404]';
                        } else if (jqXHR.status == 500) {
                            msg = 'Internal Server Error [500].';
                        } else if (exception === 'parsererror') {
                            msg = 'Requested JSON parse failed.';
                        } else if (exception === 'timeout') {
                            msg = 'Time out error.';
                        } else if (exception === 'abort') {
                            msg = 'Ajax request aborted.';
                        } else {
                            msg = 'Uncaught Error.\n' + jqXHR.responseText;
                        }
                        console.log(msg);
                    }
                });
            }
            // function for sending SMS 

            // For checkout button to send sms
            function haveverify(event) {
                var valnum =  $("#opt-number").val();
                $.ajax({
                    headers: { "Accept": "application/json"},
                    type: 'POST',
                    url: '<?php echo $block->getBaseUrl();?>verify_code.php',
                    crossDomain: true,
                    data:{method:2,code:valnum,refrence_number:refrence_number},
                    beforeSend: function(xhr){
                        xhr.withCredentials = true;
                    },
                    success: function(data, textStatus, request){
                        if(parseInt(data) == 1){
                        $("#checkout_flag").val("1");
                        $("#success-valid-code").text("Verified mobile number successfully");
                        $(".otp-error").hide();
                        $(".otp-success").show();
                        $("#timer_run").hide();
                        $("#opt-number").attr("disabled", true);
                        $("#opt_SMS").hide();
                        $("#opt_checkout").hide();
                        }else if(parseInt(data) == 2){
                           $(".opt-error-msg").val( "Code not Exsist");
                           $(".otp-success").hide();
                           if($("#opt_checkout").hide()) {
                               $("#opt_checkout").show();
                            }
                        }else if(parseInt(data) == 3){
                            // $(".opt-error-msg").val( "Code Expire");
                            $("#empty-invalid-otp").text( "Code Expire");
                            $(".otp-error").show();
                            $(".otp-success").hide();
                            if($("#opt_checkout").hide()) {
                               $("#opt_checkout").show();
                            }
                        }else if(parseInt(data) == 4){
                            $("#empty-invalid-otp").text( "Invalid OTP");
                            $(".otp-success").hide();
                            $(".otp-error").show();
                            if($("#opt_checkout").hide()) {
                               $("#opt_checkout").show();
                            }
                            if($("#timer_run").hide()) {
                                $("#timer_run").show();
                            }
                        }else if(parseInt(data) == 5){
                            $("#empty-invalid-otp").text( "Invalid OTP");
                            $(".otp-success").hide();
                            $(".otp-error").show();
                            if($("#opt_checkout").hide()) {
                               $("#opt_checkout").show();
                            }
                            if($("#timer_run").hide()) {
                                $("#timer_run").show();
                            }
                        }
                    },error: function (jqXHR, exception) {
                        var msg = '';
                        if (jqXHR.status === 0) {
                            msg = 'Not connect.\n Verify Network.';
                        } else if (jqXHR.status == 404) {
                            msg = 'Requested page not found. [404]';
                        } else if (jqXHR.status == 500) {
                            msg = 'Internal Server Error [500].';
                        } else if (exception === 'parsererror') {
                            msg = 'Requested JSON parse failed.';
                        } else if (exception === 'timeout') {
                            msg = 'Time out error.';
                        } else if (exception === 'abort') {
                            msg = 'Ajax request aborted.';
                        } else {
                            msg = 'Uncaught Error.\n' + jqXHR.responseText;
                        }
                        console.log(msg);
                    }
                });
            }
            // For checkout button to send sms

            /*______  For resend sms again _______ */
            function haveresend(event) {
                <?php if($block->getAddress()->getId()) { $event = 'EditAdrress'; } else { $event = 'NewAdrress'; } ?>
                var eventg = '<?php echo $event; ?>';
                $num= $("input[name=telephone]").val();
                if($num.length >= 10 ){// $num has + with countrt code
                    var s2 = $num.substr(1);
                    text = 971+s2;
                }else {// worong format
                    $("#modal-title-0").text('Invalid Number');
                    alert("Number not Valid");
                    return false;
                }
                $.ajax({
                    headers: { "Accept": "application/json"},
                    type: 'POST',
                    url: '<?php echo $block->getBaseUrl();?>sms.php?method=1&phone='+text+'&event='+eventg+'&is_expired=1',
                    crossDomain: true,
                    beforeSend: function(xhr){
                        xhr.withCredentials = true;
                    },
                    success: function(data, textStatus, request){
                        // $(".modal-title").text("Resend OPT have sent to You");
                        $("#otp_send_confirm").text("An OTP (One Time Passcode) has been sent to");
                        $("#mobileNumber_otp").text($num + '. ' + 'Please enter the OTP in the field below to verify.');
                        $("#success-valid-code").text("OTP send successfully");
                        $(".otp-error").hide();
                        $(".otp-success").show();
                        refrence_number = data;
                        // var timeLeft = 120;
                        var elem = document.getElementById('modal-title-0');
                        var timer_elem = document.getElementById('timer_run');
                        $("#opt_SMS").attr("disabled", true);
                        var timerId;
                        timerId = setInterval(countdown, 1000);
                        document.getElementById('counter_timer').value = 120;
                        var timeLeft = document.getElementById('counter_timer').value;
                        
                        function countdown() {
                            if (timeLeft == 0) {
                                clearTimeout(timerId);
                                timer_elem.innerHTML = 'Your OTP Code is Expire';
                                document.getElementById('counter_timer').value = timeLeft;
                                 $("#opt_SMS").removeAttr("disabled");
                                // $("#opt_SMS").attr("disabled", true);
                            } else {
                                timer_elem.innerHTML = timeLeft + ' seconds remaining';
                                timeLeft--;
                                document.getElementById('counter_timer').value = timeLeft;
                            }
                        }
                        
                        console.log(data);
                    },error: function (jqXHR, exception) {
                        var msg = '';
                        if (jqXHR.status === 0) {
                            msg = 'Not connect.\n Verify Network.';
                        } else if (jqXHR.status == 404) {
                            msg = 'Requested page not found. [404]';
                        } else if (jqXHR.status == 500) {
                            msg = 'Internal Server Error [500].';
                        } else if (exception === 'parsererror') {
                            msg = 'Requested JSON parse failed.';
                        } else if (exception === 'timeout') {
                            msg = 'Time out error.';
                        } else if (exception === 'abort') {
                            msg = 'Ajax request aborted.';
                        } else {
                            msg = 'Uncaught Error.\n' + jqXHR.responseText;
                        }
                        console.log(msg);
                    }
                });
                return false;
            }
            /*______  For resend sms again _______ */

        });
   
</script>
