<?php $dataHelper = $block->getHelper(); ?>
<?php if ($this->getAllowGlobal()): ?>
    <div class="headertopfixbottom stickytopfixbottom" id="myHeadertopfixbottom">
        <div class="ourbarfixbottom">
            <span>
                <?php echo $this->getContent(); ?> 
            </span>
            <?php if ($dataHelper->getAllowClosed() == 1): ?>
                <span class="topfix-closebottom">
                    <a title="<?php echo __('dismiss this notification'); ?>">×</a>
                </span>
            <?php endif; ?>            
        </div>
    </div>
    <?php if ($dataHelper->getDefaultStyling() == 1): ?>
        <style>
            /* Style the header */
            .headertopfixbottom {
                padding: 10px 16px;
                background: #555;
                color: #f1f1f1;
                text-align:center;
            }

            /* Page content */
            .contenttopfixbottom {
                padding: 16px;

            }
            <?php if($dataHelper->getFixedNotificationBar()): ?>
            /* The sticky class is added to the header with JS when it reaches its scroll position */
            .stickytopfixbottom {
                position: fixed;
                bottom: 0;
                left: 0;
                width: 100%;
                z-index: 1000;
            }
 
            /* Add some top padding to the page content to prevent sudden quick movement (as the header gets a new position at the top of the page (position:fixed and top:0) */
            .stickytopfixbottom + .contenttopfixbottom {
                padding-top: 102px;
            }
            <?php endif; ?>
            .headertopfixbottom span.topfix-closebottom { 
                background-color: #FAD163;
                border: 2px solid #735005;
                cursor: pointer;
                display: block;
                float: right;
                margin-right: 20px;
                padding-left: 4px;
                padding-right: 4px;
                text-decoration: none; 
            }
            .headertopfix .topfix-closebottom a { 
                text-decoration: none; 
                color: #735005; }
            .headertopfix .topfix-closebottom a:hover { 
                text-decoration: none; 
            }
        </style>
    <?php endif; ?>
    <script>

        require([
            'jquery',
            'jquery/jquery.cookie'
        ], function ($) {
            /*window.onscroll = function () {
                //topfixFunction()
            };*/

    // Get the header
            //var header = document.getElementById("myHeadertopfixbottom");
    // Get the offset position of the navbar
            //var sticky = header.offsetTop;
    <?php if ($dataHelper->getAllowClosed() == 1): ?>
                $('.headertopfixbottom .topfix-closebottom').on("click", function () {
                    //$.cookie("<?php echo $block::COOKIE_TNF; ?>", 1, {path: '/', expires: new Date((new Date()).getTime() + <?php echo $dataHelper->getAllowClosedSecond() ?> * 1000)});
                    createCookie('<?php echo $block::COOKIE_TNF; ?>', 1,<?php echo $dataHelper->getAllowClosedSecond() ?>);
                    $(".headertopfixbottom").fadeOut(100, "linear");
                });
    <?php endif; ?>
            /*
            function readCookie(name) {
                var nameEQ = name + '=';
                var ca = document.cookie.split(';');
                for (var i = 0; i < ca.length; i++) {
                    var c = ca[i];
                    while (c.charAt(0) == ' ')
                        c = c.substring(1, c.length);
                    if (c.indexOf(nameEQ) == 0)
                        return c.substring(nameEQ.length, c.length);
                }
                return null;
            }*/
            function createCookie(name, value, days) {
                if (days) {
                    var date = new Date();
                    date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
                    var expires = ';expires=' + date.toGMTString();
                }
                else
                    var expires = '';
                document.cookie = name + '=' + value + expires + '; path=/';
            }

    // Add the sticky class to the header when you reach its scroll position. Remove "sticky" when you leave the scroll position
            function topfixFunction() {
                if (window.pageYOffset > sticky) {
                    header.classList.add("stickytopfixbottom");
                } else {
                    header.classList.remove("stickytopfixbottom");
                }
            }
        });

    </script>
<?php endif; ?>