<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Widget\Telephone $block */
?>

<div class="field telephone <?= $block->isRequired() ? 'required' : '' ?>">
    <label for="telephone" class="label">
        <span>
            <?= $block->escapeHtml(__('Phone Number (Minimum Length: 10)')) ?>
        </span>
    </label>
    <div class="control">
        <?php
            $_validationClass = $block->escapeHtmlAttr(
                $this->helper('Magento\Customer\Helper\Address')
                     ->getAttributeValidationClass('telephone')
            );
        ?>
        <input type="text"
               name="telephone"
               id="telephone"
               minlength="10"
		maxlength="10"
               placeholder="Ex:05xxxxxxxx"
               value="<?= $block->escapeHtmlAttr($block->getTelephone()) ?>"
               title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
               class="input-text <?= $_validationClass ?: '' ?> customer_ph_number"
               data-mage-init='{"mage/trim-input":{}}'
               data-validate="{'validate-number':true}"
               data-telephone-min-length=10
        >
    </div>
</div>
