<?php
/**
 * Copyright © 2018 IWD Agency - All rights reserved.
 * See LICENSE.txt bundled with this module for license details.
 */
?>
<?php /** @var \IWD\BluePaySubs\Block\Customer\Subscriptions\Edit\Tab\ShippingAddress $block */ ?>
<?php $formId = $block->escapeHtml($block->getFormId()); ?>
<?php $submitUrl = $block->escapeUrl($block->getSubmitUrl()); ?>
<form id="<?php echo $formId ?>" action="<?php echo $submitUrl ?>" method="post" enctype="multipart/form-data">
    <div class="fieldset-wrapper" data-bind="scope: 'shipping_address'">
        <fieldset
                data-bind="attr: {class: 'fieldset shipping_address items ' + getCode(), id: 'shipping_address_form_' + getCode()}">
            <?= $block->getBlockHtml('formkey') ?>
            <!-- ko if: (getAddresses())-->
            <div class="field" data-bind="attr: {id: getCode() + '_choose_shipping_address_div'}">
                <label data-bind="attr: {for: getCode() + '_choose_shipping_address'}" class="label">
                    <span><!-- ko i18n: 'Choose Address'--><!-- /ko --></span>
                </label>
                <div class="control">
                    <div class="fields">
                        <div class="field no-label">
                            <div class="control">
                                <select name="shipping[address_id]"
                                        class="select"
                                        data-bind="attr: { id: getCode() + '_choose_shipping_address'},
                                            options: getAddresses(),
                                            optionsValue: 'value',
                                            optionsText: 'label',
                                            value: selectedAddressId
                                        ">
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /ko -->
        </fieldset>
    </div>
    <div class="fieldset-wrapper">
        <fieldset class="fieldset new_shipping_address items">
            <div class="field name">
                <div class="control">
                    <div class="fields group group-2">
                        <div class="field firstname required">
                            <label for="shipping_firstname" class="label">
                                <span><?= $block->escapeHtml(__('First Name')) ?></span>
                            </label>
                            <div class="control">
                                <input type="text" class="input-text firstname required"
                                       name="shipping[firstname]" id="shipping_firstname"
                                       title="<?= $block->escapeHtml(__('First Name')) ?>"
                                       />
                            </div>
                        </div>
                        <div class="field lastname required">
                            <label for="shipping_lastname" class="label">
                                <span><?= $block->escapeHtml(__('Last Name')) ?></span>
                            </label>
                            <div class="control">
                                <input type="text" class="input-text lastname required"
                                       name="shipping[lastname]" id="shipping_lastname"
                                       title="<?= $block->escapeHtml(__('Last Name')) ?>"
                                       />
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>
            <div class="field street required">
                <label for="street_1" class="label">
                    <span><?= $block->escapeHtml(__('Street Address')) ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="shipping[street_1]"
                           title="<?= $block->escapeHtml(__('Street Address')) ?>"
                           id="shipping-street_1"
                           class="input-text <?= $block->escapeHtml($_streetValidationClass) ?>"/>
                    <div class="nested">
                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                        <?php for ($_i = 1, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i < $_n; $_i++): ?>
                            <div class="field additional">
                                <label class="label" for="street_<?= /* @noEscape */ $_i + 1 ?>">
                                    <span><?= $block->escapeHtml(__('Street Address %1', $_i + 1)) ?></span>
                                </label>
                                <div class="control">
                                    <input type="text" name="shipping[street_<?= /* @noEscape */ $_i + 1 ?>]"
                                           title="<?= $block->escapeHtml(__('Street Address %1', $_i + 1)) ?>"
                                           id="shipping-street_<?= /* @noEscape */ $_i + 1 ?>"
                                           class="input-text <?= $block->escapeHtml($_streetValidationClass) ?>">
                                </div>
                            </div>
                        <?php endfor; ?>
                    </div>
                </div>
            </div>

            <?php if ($this->helper('Magento\Customer\Helper\Address')->isVatAttributeVisible()) : ?>
                <div class="field taxvat">
                    <label class="label" for="vat_id">
                        <span><?= $block->escapeHtml(__('VAT Number')) ?></span>
                    </label>
                    <div class="control">
                        <input type="text"
                               name="shipping[vat_id]"
                               title="<?= $block->escapeHtml(__('VAT Number')) ?>"
                               class="input-text <?= $block->escapeHtml($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('vat_id')) ?>"
                               id="shipping-vat-id">
                    </div>
                </div>
            <?php endif; ?>
            <div class="field country required">
                <label class="label" for="country"><span><?= $block->escapeHtml(__('Country')) ?></span></label>
                <div class="control">
                    <?= $block->getCountryHtmlSelect(null, 'country_id', 'shipping-country', 'Shipping Country') ?>
                </div>
            </div>
            <div class="field name required">
                <div class="control">
                    <div class="fields group group-3">
                        <div class="field city required">
                            <label class="label" for="city"><span><?= $block->escapeHtml(__('City')) ?></span></label>
                            <div class="control">
                                <input type="text"
                                       name="shipping[city]"
                                       title="<?= $block->escapeHtml(__('City')) ?>"
                                       class="input-text <?= $block->escapeHtml($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city')) ?>"
                                       id="shipping-city">
                            </div>
                        </div>
                        <div class="field region required">
                            <label class="label" for="region_id">
                                <span><?= $block->escapeHtml(__('State/Province')) ?></span>
                            </label>
                            <div class="control">
                                <select id="shipping-region_id" name="shipping[region_id]"
                                        title="<?= $block->escapeHtml(__('State/Province')) ?>"
                                        class="validate-select">
                                    <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                                </select>
                                <input type="text"
                                       id="shipping-region"
                                       name="shipping[region]"
                                       title="<?= $block->escapeHtml(__('State/Province')) ?>"
                                       class="input-text <?= $block->escapeHtml($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region')) ?>"/>
                            </div>
                        </div>
                        <div class="field zip required">
                            <label class="label" for="shipping-zip">
                                <span><?= $block->escapeHtml(__('Zip/Postal Code')) ?></span>
                            </label>
                            <div class="control">
                                <input type="text"
                                       name="shipping[postcode]"
                                       title="<?= $block->escapeHtml(__('Zip/Postal Code')) ?>"
                                       id="shipping-zip"
                                       class="input-text validate-zip-international <?= $block->escapeHtml($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode')) ?>">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php $phoneValidation = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone'); ?>
            <div class="field telephone<?php if (strpos($phoneValidation, 'required') !== false): ?> _required<?php endif; ?>">
                <label class="label" for="shipping-telephone"><span><?php echo $block->escapeHtml(__('Phone Number')) ?></span></label>
                <div class="control">
                    <input type="text" name="shipping[telephone]" title="<?php echo $block->escapeHtml(__('Phone Number')) ?>" class="input-text <?php echo $block->escapeHtml($phoneValidation) ?>" id="shipping-telephone" data-validate='{required:true}'>
                </div>
            </div>
        </fieldset>
    </div>

    <div class="actions">
        <button class="secondary subs-update" type="submit">
            <span><?php /* @escapeNotVerified */
                echo __('Update') ?></span>
        </button>
        <button class="secondary cancel subs-cancel" type="button">
            <span><?php /* @escapeNotVerified */
                echo __('Cancel') ?></span>
        </button>
    </div>
</form>

<script type="text/x-magento-init">
    {
        "#<?= $formId ?>": {
            "validation": {}
        },
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "shipping_address": {
                        "component": "IWD_BluePaySubs/js/view/shipping_address",
                        "config":  <?= /* @escapeNotVerified */ $block->getConfig() ?>
                    }
                }
            }
        },
        "#<?= $formId ?> #shipping-country": {
            "regionUpdater": {
                "optionalRegionAllowed": "true",
                "regionListId": "#shipping-region_id",
                "regionInputId": "#shipping-region",
                "postcodeId": "#shipping-zip",
                "form": "#<?= $formId ?>",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "0",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>