<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php if($_catdescription = $block->getCurrentCategory()->getData('category_description')): ?>
<?php $_name = $block->getCurrentCategory()->getName() ?>
		<div class="categ-content">
			<h3><?php echo $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_name, 'name'); ?></h3>
		    <div class="content-cat">
              <?php echo $_catdescription = $block->getCurrentCategory()->getData('category_description'); ?>
		    </div>
		</div>
 <?php  endif; ?>