<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>

    
<?php
//$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
//$category = $block->getCurrentCategory();//get current category
//$subcats = $category->getChildrenCategories();
//$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $catId = $block->getCurrentCategory()->getId();  //Parent Category ID
    $subCategory = $objectManager->create('Magento\Catalog\Model\Category')->load($catId);
    $subCats = $subCategory->getChildrenCategories();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php $media = str_replace("/index.php", "", $block->getBaseUrl()); ?>
<?php if($subCats && count($subCats) > 0){ ?>
<ul class="category-slider owl-carousel">
    <?php
    foreach ($subCats as $subcat) {
        $_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
        $subcaturl = $subcat->getUrl();
        $_imgHtml = '';
        $_imgUrl = $_category->getImageUrl();
        if ($_imgUrl = $_category->getImageUrl()) {
            $_imgHtml = '<img src="' . $_imgUrl . '" class="cat-img"/>';
            $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
        } else{$_imgHtml = '<img src="' .$media.'/pub/media/custom/default-img.jpg"  width="200" />'; }  ?>
        <li class="cat-li">
            <div class="cat-image">
                <a href="<?php echo $subcaturl ?>">
                    <?php echo $_imgHtml;?>
                    <h4><?php echo $subcat->getName(); ?></h4>
                </a>
            </div>
        </li>
    <?php } ?>
</ul>
<?php }?>

    <script type="text/javascript">
            require([
                'jquery',
                'owlcarousel'
            ], function ($) {
                $(".owl-carousel").owlCarousel({
                    responsive: {
                        0: {
                            items: 3,
                            nav: <?php echo (count($subCats) > 1 ) ? 'true' : 'false'; ?>
                        },
                        480: {
                            items: 3,
                            nav: <?php echo (count($subCats) > 1 ) ? 'true' : 'false'; ?>
                        },
                        768: {
                            items: 3,
                            nav: <?php echo (count($subCats) > 1 ) ? 'true' : 'false'; ?>
                        },
                        992: {
                            items: 4
                        },
                        1200: {
                            items: 5
                        },
                    }, 
                    autoplay: false,
                    loop: true,
                    nav: <?php echo (count($subCats) > 4 ) ? 'true' : 'false'; ?>,
                    dots: false,
                    autoplayHoverPause: true,
                    margin: 5
                });
            });
        </script>