<script type="text/javascript" defer="defer" src="<?php echo $block->getViewFileUrl('/') . '/js/custom.js' ?>"></script>
<script type="text/javascript" defer="defer" src="<?php echo $block->getViewFileUrl('/') . '/js/sms-otp.js' ?>"></script>
<script type="text/javascript" defer="defer" src="<?php echo $block->getViewFileUrl('/') . '/js/jquery.show-more.js' ?>"></script>
<script async defer="defer" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBz7TCveNfJdTAPxtqMh2DJfg0iGpubFbY"></script>
<!-- <script type="text/javascript" defer="defer">
	 require([
		'jquery', 'Magento_Checkout/js/view/sidebar'], function ($) {
		});
</script> -->