<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= /* @escapeNotVerified */ __('Sort By') ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
            <?php if($_key == 'price' || $_key == 'name' || $_key == 'position' || $_key == 'sort_list') { } else { ?>
            <option value="<?= /* @escapeNotVerified */ $_key ?>"
                <?php if ($block->isOrderCurrent($_key)): ?>
                    selected="selected"
                <?php endif; ?>
                >
                <?= $block->escapeHtml(__($_order)) ?>
            </option>
        <?php } ?>
        <?php endforeach; ?>

         <!-- Price Low To High -->
            <option value="<?= /* @escapeNotVerified */ 'price'.'&product_list_dir=asc' ?>"
                <?php if (($block->isOrderCurrent('price', 'asc') && $this->getCurrentDirection() == 'asc')): ?>
                    selected="selected"
                <?php endif; ?>
                >
                <?= $block->escapeHtml(__('Price Low to High')) ?>
            </option>
         <!-- Price Low To High -->
         
        <!-- Price High To Low -->
        <option value="<?= /* @escapeNotVerified */ 'price'.'&product_list_dir=desc' ?>"
                <?php if (($block->isOrderCurrent('price', 'desc') && $this->getCurrentDirection() == 'desc')): ?>
                    selected="selected"
                <?php endif; ?>
                >
                <?= $block->escapeHtml(__('Price High to Low')) ?>
        </option>
         <!-- Price High To Low -->
         
         <!-- Name A to Z -->
            <option value="<?= /* @escapeNotVerified */ 'name'.'&product_list_dir=asc' ?>"
                <?php if (($block->isOrderCurrent('name', 'asc') && $this->getCurrentDirection() == 'asc')): ?>
                    selected="selected"
                <?php endif; ?>
                >
                <?= $block->escapeHtml(__('Name A to Z')) ?>
            </option>
        <!-- Name A to Z -->

         <!-- Name Z to A -->
             <option value="<?= /* @escapeNotVerified */ 'name'.'&product_list_dir=desc' ?>"
                <?php if (($block->isOrderCurrent('name', 'desc') && $this->getCurrentDirection() == 'desc')): ?>
                    selected="selected"
                <?php endif; ?>
                >
                <?= $block->escapeHtml(__('Name Z to A')) ?>
            </option>
         <!-- Name Z to A -->
         
          <!-- Newest -->
          <!-- Newest -->

         <!-- BestSeller -->
            <option value="<?= /* @escapeNotVerified */ 'sort_list'.'&product_list_dir=desc' ?>"
                <?php if (($block->isOrderCurrent('sort_list', 'desc') && $this->getCurrentDirection() == 'desc')): ?>
                    selected="selected"
                <?php endif; ?>
                >
                <?= $block->escapeHtml(__('Bestsellers')) ?>
            </option>
         <!-- BestSeller -->

    </select>
    <?php if ($block->getCurrentDirection() == 'desc'): ?>
      <!--   <a title="<?= /* @escapeNotVerified */  __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
            <span><?= /* @escapeNotVerified */ __('Set Ascending Direction') ?></span>
        </a> -->
    <?php else: ?>
      <!--   <a title="<?= /* @escapeNotVerified */ __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
            <span><?= /* @escapeNotVerified */ __('Set Descending Direction') ?></span>
        </a> -->
    <?php endif; ?>
   
   <!-- Limiter Here -->
    <div class="field limiter">
       <label class="label" for="limiter">
            <span><?= /* @escapeNotVerified */ __('Show') ?></span>
        </label>
        <div class="control">
            <select id="limiter" data-role="limiter" class="limiter-options">
                <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
                    <option value="<?= /* @escapeNotVerified */ $_key ?>"<?php if ($block->isLimitCurrent($_key)): ?>
                        selected="selected"<?php endif ?>>
                        <?= /* @escapeNotVerified */ $_limit ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
        <span class="limiter-text"><?= /* @escapeNotVerified */ __('per page') ?></span>
    </div>
    
   <!-- Limiter Here -->
</div>
