<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Aheadworks\AdvancedReports\Block\Adminhtml\View $block */
?>
<?php /* @noEscape */ echo $block->getChildHtml('index-info') ?>
<div class="aw-arep-report_content-top">
    <div class="aw-arep-report_left-position"><?php /* @noEscape */ echo $block->getChildHtml('breadcrumbs') ?></div>
    <div class="aw-arep-report_clear"></div>
</div>
<div class="aw-arep-report_grid">
    <?php /* @noEscape */ echo $block->getChildHtml('grid') ?>
</div>
